/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MarkovProbabilities */

#ifndef _Included_MarkovProbabilities
#define _Included_MarkovProbabilities
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MarkovProbabilities
 * Method:    callPrologGetReachability
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_MarkovProbabilities_callPrologGetReachability
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
